---
- name: User Managment
  hosts: all
  become: true
  become_user: root

  tasks: 
    - name: User creation
      user:
        name: mansi
        comment: new user adding for devops team
        home: /home/mansi
        shell: /bin/bash


